name: Update PEPs

on:
  # Update PEPS every day at midnight
  schedule:
    - cron: '0 0 * * *'

  # Allow to trigger the job manually
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run from'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Update PEPs
      run: bash script.sh

    - name: Get the current PEPs revision
      id: current_rev
      run: |
        cd peps
        echo "rev=$(git log --oneline --max-count=1 --abbrev | cut -d' ' -f1)" >> $GITHUB_OUTPUT
        cd ..

    - name: Push changes
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: master
        commit_message: "PEPs: upgrade to rev ${{ steps.current_rev.outputs.rev }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
